const FRAMERATE = 1000 / 60
const BOARDSIZE = 20
const PATCHSIZE = 30 //px
const BOARDSIZE_IN_PX = BOARDSIZE * PATCHSIZE
const PLANT_MATURITY_AGE = 3000 / FRAMERATE // msec
const MAX_TIMESCALE = 250
const MIN_TIMESCALE = 50

export {
  FRAMERATE,
  BOARDSIZE,
  PATCHSIZE,
  BOARDSIZE_IN_PX,
  PLANT_MATURITY_AGE,
  MAX_TIMESCALE,
  MIN_TIMESCALE
}
